### ISSUE TITLE
SVSegmentedControl.m

### ISSUE THREAD

**Issue by jrespuny** [samvermette/SVSegmentedControl#11]
- (void)willMoveToSuperview:(UIView *)newSuperview {
  
  if(newSuperview == nil)
      return;
  
  int c = [self.titlesArray count];
  int i = 0;

// self.segmentWidth = 0;

```
self.segmentWidth = (([UIScreen mainScreen].bounds.size.width) / (([self.titlesArray count] == 0)?1:[self.titlesArray count]));
```

**Comment by jrespuny** [comment]
How about giving some option for the widht so that it does not depend on its contents?

**Comment by samvermette** [comment]
You can increase the `titleEdgeInsets` if you want the sections to be larger.
