### ISSUE TITLE
Wrong callback using "changeHandler" block

### ISSUE THREAD

**Issue by nightbirdsevolve** [samvermette/SVSegmentedControl#12]
This problem doesn't occur using the target-action method
On the first example, changeHandler is triggered when the thumb hits the right side of the segment, not on "mouse up"
so for example you could keep sliding the thumb back to position 0 and it would still think it is at index 1...

**Comment by samvermette** [comment]
Good call. Will fix shortly, thanks!

**Comment by samvermette** [comment]
Fixed this with my last commit. Sorry it took so long!
