### ISSUE TITLE
White tint color

### ISSUE THREAD

**Issue by massimoksi** [samvermette/SVSegmentedControl#14]
Setting the tint color as white has practically no effect since the background of the segmented control will remain a dark gray gradient.

**Comment by samvermette** [comment]
You want the thumb to be white or the control's background?

**Comment by massimoksi** [comment]
I have problems with the background of the segmented control. The Thumb works fine.

**Comment by samvermette** [comment]
"No effect" is not quite right. See top (whiteColor) vs bottom (default grayColor): http://cl.ly/Doyb

I guess this would be a tintColor limitation similar to what UIKit has (try setting a navigation bar's tintColor to white, it looks terrible).

**Comment by massimoksi** [comment]
You're right, but the result was not exactly what I was expecting. In the end I can use backgroundImage for my intent. You can close this issue if you want.

**Comment by sobri909** [comment]
Old issue, but I'm new to this control, so it's new to me.

A _very_ cool control! But it doesn't work in its current incarnation for light designs. `tintColor = UIColor.whiteColor` produces something that's below 0.5 brightness.

I'll see if I can come up with a patch. Only been fiddling for a few minutes, so not sure how deep it goes yet. But ideally tintColors across the whole brightness spectrum should be possible.
