### ISSUE TITLE
UIControlEventValueChanged Firing on Creation

### ISSUE THREAD

**Issue by VeeruPV** [samvermette/SVSegmentedControl#15]
Hi there,
Your control is awesome and thanks for all the hard work.

I am having a minor issue with the event UIControlEventValueChanged - i have a selector for the event, but i do not want the selector to fire when the control is created. In this case, the event is fired in the start when the control is created.

How can i avoid it? Ofcourse without having to manually creating a flag variable.

Regards

**Comment by runmad** [comment]
When creating the SVSegmentedControl, are you setting the selected index?

**Comment by samvermette** [comment]
Not sure why I didn't reply to this earlier, but you should now use `setSelectedSegmentIndex:animate:` to set the selected segment index. All other methods are now either gone or deprecated. Calling that method doesn't fire a `UIControlEventValueChanged` event.
