### ISSUE TITLE
Changing 'selectedIndex' property after adding instance to view has no effect. (solution: use moveThumbToIndex:animate:  instead)

### ISSUE THREAD

**Issue by JEXcome** [samvermette/SVSegmentedControl#16]
Hi all.
I was implementing the "set defaults" routine for  some  instances of SVSegmentedControl, but I have trouble with setting selectedIndex' property.

The code below will be enough to perform this situation :

```
SVSC = [[SVSegmentedControl alloc] initWithSectionTitles:[NSArray arrayWithObjects:@"zero", @"one", nil]];

// some customization ...

SVSC.selectedIndex = 1;

[self.workArea addSubview:SVSC ];

SVSC.selectedIndex = 0;
```

In result I have selected the item "one", not "zero".

Is there any suggestion how to this manipulation take effect?
Or maybe i'm do something wrong?

**Comment by samvermette** [comment]
Have you tried setting `selectedIndex` before adding the segmentedControl to the view?

**Comment by JEXcome** [comment]
yes, changing selectedIndex property before adding control to view works great.
But I need possibility  to change this programmatically after user have made some manipulation (set to default desired state)

**Comment by samvermette** [comment]
try using `moveThumbToIndex:animated:` instead and let me know if that works.

**Comment by JEXcome** [comment]
Thank You very much! This method have helped me.  moveThumbToIndex:animate:  working perfect. 
But "animate", not "animated", I was confused with this for few minutes :)

Maybe You should add this description on project's page near the Customization examples?

**Comment by samvermette** [comment]
Yeah the distinction between that method and the selectedIndex property isn't very clear. I'm going to reopen this issue to remind me to fix this.
