### ISSUE TITLE
Background color change

### ISSUE THREAD

**Issue by reejosamuel** [samvermette/SVSegmentedControl#19]
I'm trying to change the background color of the segment itself NOT the slider to White.

I tried changing segment.backgroundColor and segment.tintcolor to White but it wouldn't change. 

Please help

**Comment by samvermette** [comment]
No idea why I haven't replied to this earlier. Are you setting the `backgroundColor` before adding the segmented control to its superview?

**Comment by HamzaGhazouani** [comment]
Change that in DrawRect of SVSegmentedControl Class ;-)

 // background tint
        CGFloat components[4] = { 0.0/255.00, 51.0/255.0, 91.0/255.0, 1};
