### ISSUE TITLE
About support without ARC

### ISSUE THREAD

**Issue by carl2007** [samvermette/SVSegmentedControl#21]
I'm sorry, my app not use ARC, and I'm new to the iPhone develop.
Is there any good way to support this project without ARC.

**Comment by carl2007** [comment]
Sorry, a stupid question. Please close it. Thank you.

And thank you for your hard work, it works fine for me.

**Comment by samvermette** [comment]
Just in case: you can find the last non-ARC version on the [last-mrc](https://github.com/samvermette/SVSegmentedControl/tree/last-mrc) branch.
