### ISSUE TITLE
There is a way to add it on a UITableViewCell?

### ISSUE THREAD

**Issue by Piero87** [samvermette/SVSegmentedControl#24]
Hello, i have a uitableview, with different type of cell, that display different value, and i want insert the SVSegmentedControl, only on one specific UITableViewCell, i have tried using cell.contentView addsubivew on that specfic cell, but if i scroll the uitableview fast i see the SVSegmentedControl also on other cell, so my question is there is a way to insert the UITableViewCell only on a specific cell?

**Comment by samvermette** [comment]
@Piero87 sounds like you aren't properly using the cell reuse identifier. Make sure you give that cell a different reuseIdentifier in `dequeueReusableCellWithIdentifier:` and `initWithStyle:reuseIdentifier:`. Your `tableView:cellForRowAtIndexPath:` should therefore be able to return 2 kinds of cells, 1 that contains the segmented control and the other regular cells. Did you even subclass `UITableViewCell` to make this cell?
