### ISSUE TITLE
Cancel index changes for every tap

### ISSUE THREAD

**Issue by eyalc82** [samvermette/SVSegmentedControl#25]
Hey thanks for sharing, 

I see that with a two section segmented control the selected index changes for every tap, even if same section was tapped.
For example if now the selected index is 1, and I tap on section 1 the index will now change to 2, although i didn't tap on 2 I re-tap on 1..
Is there a way to cancel this behavior?

**Comment by samvermette** [comment]
This is the intended behavior. UISwitches work like this. Tapping a 2-segments control should toggle the selection index.
