### ISSUE TITLE
Change handler block can cause a retain cycle.

### ISSUE THREAD

**Issue by tarnfeld** [samvermette/SVSegmentedControl#28]
I'm getting the following warning in XCode 4.5 when I use some code like this. I have the segmented control as a private ivar in the view controller.

![warning](http://f.cl.ly/items/132u233Y0T3u0v1G411n/Screen%20Shot%202012-09-10%20at%2007.07.55.png)

``` objc
[__segmentedControl setChangeHandler:^(NSUInteger index) {
    [self fooBar:index + 1];
}];
```

This is due to the fact the segmented control class retains the block (therefore causing a retain cycle). Could you suggest anything?

Thanks! Awesome work!

**Comment by samvermette** [comment]
@tarnfeld this is not specific to SVSegmentedControl. See http://stackoverflow.com/a/7854315/87158

**Comment by tarnfeld** [comment]
Brilliant, thanks!
