### ISSUE TITLE
issue When i added the -fobjc-arc

### ISSUE THREAD

**Issue by sivasankarp** [samvermette/SVSegmentedControl#29]
HI 

  Nice work by you,Currently when i tried using your code im facing issues.
mine is NON - ARC.i have even followed your instructions as follows 
Important note if your project doesn’t use ARC: you must add the -fobjc-arc compiler flag to SVSegmentedControl.m in Target Settings > Build Phases > Compile Sources.

but still im facing the problem.mine is Xcode4.2 

Thanks
Siva

**Comment by samvermette** [comment]
@sivasankarp what's the error you're getting? Why not update to Xcode 4.5?

**Comment by sivasankarp** [comment]
Receiver type 'SVSegmentedControl' for instance message does not declare a method with selector 'setThumbSecondValuesForIndex:'
Currently im getting this issue.With 14 errors :
GenerateDSYMFile /Users/imfuser/Library/Developer/Xcode/DerivedData/SVSegmentedControl-cmiqkzhhqzxvkgghxwznfxdcyllz/Build/Products/Debug-iphonesimulator/SVSC.app.dSYM /Users/imfuser/Library/Developer/Xcode/DerivedData/SVSegmentedControl-cmiqkzhhqzxvkgghxwznfxdcyllz/Build/Products/Debug-iphonesimulator/SVSC.app/SVSC
    cd /Users/imfuser/Desktop/SVSegmentedControl-master/Demo
    setenv PATH "/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Developer/usr/bin/dsymutil /Users/imfuser/Library/Developer/Xcode/DerivedData/SVSegmentedControl-cmiqkzhhqzxvkgghxwznfxdcyllz/Build/Products/Debug-iphonesimulator/SVSC.app/SVSC -o /Users/imfuser/Library/Developer/Xcode/DerivedData/SVSegmentedControl-cmiqkzhhqzxvkgghxwznfxdcyllz/Build/Products/Debug-iphonesimulator/SVSC.app.dSYM

error: unable to open executable '/Users/imfuser/Library/Developer/Xcode/DerivedData/SVSegmentedControl-cmiqkzhhqzxvkgghxwznfxdcyllz/Build/Products/Debug-iphonesimulator/SVSC.app/SVSC'

Im using MAC os 10.6.8 so i cant able to use the latest xcode.

Can you guide me in this & it will support in older version like iOS4 & below?

**Comment by samvermette** [comment]
I think this had to do with methods missing from the class interface as well as properties not being explicitly synthesized. Both of these things automatically get handled in Xcode 4.5 (maybe before that, I'm not sure). Can you try again with the latest version and let me know?

Also, I don't see any reason for you supporting iOS 4 and below. Google the iOS adoption rate stats, virtually no one is still on iOS 4. If I were to start a new app today, I wouldn't even bother supporting iOS 5.
