### ISSUE TITLE
Delegate methods called on willMoveToSuperview:

### ISSUE THREAD

**Issue by domesticcatsoftware** [samvermette/SVSegmentedControl#3]
Not sure if this is intentional, but when adding the control to a view it calls the delegate method straight away (with the selected segment being 0).  This is because of the call to `[self moveThumbToIndex:0 animate:NO];` inside `willMoveToSuperview:`.  Removing that call fixes the problem but I'm not sure what else this might effect.

**Comment by samvermette** [comment]
Fixed. Made `selectedIndex` writable so that you can set the initially selected index and it won't trigger the delegate/block handler call. Good call, thanks!
