### ISSUE TITLE
Crossfade with images leaves ghost of alternative image

### ISSUE THREAD

**Issue by rhubarb** [samvermette/SVSegmentedControl#33]
I'm using an SVSegmentedControl with two icon images with transparency (from Glyphish.com) and with no text labels: image only. I have crossFadeLabelsOnDrag set to YES and the images crossfade just like the text would.
However, whenever I slide the thumb to the rightmost of the two segments, the image remains just slightly cross-faded so that you see a ghost of the leftmost image. It doesn't happen the other way, and it only happens if you actually do the sliding.

As a side note: the textColor and textShadowColor properties affect transparent sections of the image in this mode when there is no text - but I find that actually useful, not sure if its intentional

**Comment by samvermette** [comment]
Can you post a couple screenshots that illustrate these 2 bugs? That would help a lot. Thanks!

**Comment by rhubarb** [comment]
I have some screenshots - but where do I post them?
Note that to produce the screenshots that I want to post, I edited the demo to change yellowRC to have two images and no text like this:

```
SVSegmentedControl *yellowRC = [[SVSegmentedControl alloc] initWithSectionTitles:[NSArray arrayWithObjects:@"", @"", nil]];
yellowRC.sectionImages = [NSArray arrayWithObjects:[UIImage imageNamed:@"75-phone"],
                                                   [UIImage imageNamed:@"99-umbrella"], nil];

// Note I also changed the initial segment since it was at 2 = outside the range now I reduced it from 3 segments:
yellowRC.selectedIndex = 1;
```

The two images I'm using here are not the ones I was using with my app, but they're from the same batch and show the same problem. You can get them free with the glyphish.com free icon set. The names are as I'm using them.

Now, where can I post the screenshots?

**Comment by samvermette** [comment]
@rhubarb I usually use a service like Cloud app or Droplr. I just always assume everyone does that, but I shouldn't.

Instead of writing all that text it just would have been simpler (for both of us) to provide a screenshot. Anyway, I'll make the code changes to reproduce the bug and will fix it later tonight or tomorrow.

**Comment by samvermette** [comment]
Fixed with my last commit.

**Comment by rhubarb** [comment]
thanks for the droplr tip
