### ISSUE TITLE
Image-only segments have the image offset to the left

### ISSUE THREAD

**Issue by rhubarb** [samvermette/SVSegmentedControl#34]
This is true whenever you have only images  (and I've not tested for images + text) but you notice it especially if you have a single-segment (that's right, single - your control is very nice for use as a button in a UIBarButtonItem) and especially if the image is symmetric. See here
http://d.pr/i/x0ST
(cool service this Droplr, thanks again for the tip)

Note that the center of the Plus is left-of-center by 2 pixels.
It turns out that this is because of the 5 pixel "fudge factor" you add every time you use the image.width.
Now, I haven't attached a patch because I'm not sure of what the correct fix is, but for me simply commenting out the +5 in this line in drawRect in SVSegmentedThumb.m does the trick:

```
imageWidth = image.size.width; //+5;
```

I'm not sure about the other cases though. I was frustrated for a while trying to debug this because I though this image was being painted in drawREct in SVSegmented_Control_.m instead of the Thumb, and commenting out the 2 +5's in that class had no effect.  In any case, this single commenting-out fixes it for me, but I assume I'm breaking some other use case.
What was the fudge factor for? 

If it is indeed necessary - the correct fix might be to simply account for it when calculating the drawing position (ie subtract it from the width again)

**Comment by samvermette** [comment]
Sorry it took so long!
