### ISSUE TITLE
fadeLabelsBetweenSegments seems to be inverted

### ISSUE THREAD

**Issue by hjaltij** [samvermette/SVSegmentedControl#4]
Hi,

fadeLabelsBetweenSegments option seems to do the opposite to what I would expect it to do. When set to YES the labels don't fade but when set to NO they fade.

Thanks.
- H

**Comment by samvermette** [comment]
Oh, well, depends on the way you see it. But you're right that it's confusing. Will fix shortly, thanks.

**Comment by hjaltij** [comment]
Cool. Thanks a lot for the control though it's great =)

**Comment by samvermette** [comment]
Renamed it to `crossFadeLabelsOnDrag`. Hope this makes it more clear :)
