### ISSUE TITLE
Problem when use "changeHandler"

### ISSUE THREAD

**Issue by xuzhongzhou** [samvermette/SVSegmentedControl#48]
Hi, i find that when i user "changeHandler", my ViewController which add the SVSegmentedControl can not be dealloc.
However , it going right when i use the classic UIControl method. the ViewController can be dealloc.

**Comment by samvermette** [comment]
Can I see the code you use for your `changeHandler`? If you're referencing self, you need to assign it to a `__block` variable.

**Comment by xuzhongzhou** [comment]
Hi, this is one of my code. It, may not referencing self, however the ViewController not be dealloc.

```
switch (newIndex) {
        case 0:
        {
            segmentedIndex = 0;
            [self setVoucherView];

        }
            break;
        case 1:
        {
            segmentedIndex = 1;
            [self setVoucherView];

        }
            break;

        default:
            break;
    }
```

```
- (void)setVoucherView
{
    if (segmentedIndex == 0)
    {
        _labVoucherNum.hidden = YES;
        _imageVoucherPic.hidden = NO;
        _labPrompt.text = @"xxxxxxxxxxxxxxxx";
    }
    else if (segmentedIndex == 1)
    {  
        _labVoucherNum.hidden = NO;
        _imageVoucherPic.hidden = YES;
        _labPrompt.text = @"xxxxxxxxxxxxxxxx";
    }
}
```

_labVoucherNum and _imageVoucherPic just a Label Text and a Image

**Comment by samvermette** [comment]
Assuming that your switch lives inside the changeHandler block, then yes you're referencing self inside your block. Try something like:

```
__block id safeSelf = self;
[segmentedControl setChangeHandler:^(NSUInteger newIndex) {
    // switch....
    [safeSelf setVoucher];
}];
```

**Comment by xuzhongzhou** [comment]
Thx, this is my problem, not familiar with using block
